### ISSUE TITLE
Roadmap v1.0.0

### ISSUE THREAD

**Issue by FilipSolich** [FilipSolich/jmap#1]
# V1.0.0

## Client

- [ ] Create client struct
- [ ] Set JMAP server
- [ ] Add client HTTP basic authentication
- [ ] Add client HTTP bearer authentication
- [ ] Make basic request
- [ ] Get session

## Session

- [ ] Create session struct
- [ ] Get session from JMAP server
- [ ] Add JMAP server auto discovery
- [ ] Try different server if more are discovered

## Standard method

- [ ] `Core/echo`
- [ ] `/get`
- [ ] `/set`
- [ ] `/copy`
- [ ] `/query`
- [ ] `/queryChanges`

## Binary data

- [ ] Uploading binary data
- [ ] Downloading binary data
- [ ] `Blob/copy` 

## Examples

- [ ] Add example program

## Documentation

- [ ] Add documentation

## Tests

- [ ] Add tests
